// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvz5X_rKaYPZ1Pn3TX5819tRu0e9PcdrQ',
    appId: '1:832863065756:web:91f2563cbc39c7d5e4bf59',
    messagingSenderId: '832863065756',
    projectId: 'fluttartur',
    authDomain: 'fluttartur.firebaseapp.com',
    storageBucket: 'fluttartur.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmE7MYlgRWO0o2c3gbaXWo1lC-W18uX8U',
    appId: '1:832863065756:android:aa80776119ff27f3e4bf59',
    messagingSenderId: '832863065756',
    projectId: 'fluttartur',
    storageBucket: 'fluttartur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYYXH7rC4SZBVrha-LkluPJZortnPN8Zk',
    appId: '1:832863065756:ios:3a39c3fd12e7296be4bf59',
    messagingSenderId: '832863065756',
    projectId: 'fluttartur',
    storageBucket: 'fluttartur.appspot.com',
    iosClientId: '832863065756-ujpth26rgbqid0p9rjsan07a9bjl85uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttartur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYYXH7rC4SZBVrha-LkluPJZortnPN8Zk',
    appId: '1:832863065756:ios:3a39c3fd12e7296be4bf59',
    messagingSenderId: '832863065756',
    projectId: 'fluttartur',
    storageBucket: 'fluttartur.appspot.com',
    iosClientId: '832863065756-ujpth26rgbqid0p9rjsan07a9bjl85uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttartur',
  );
}
